---
driver:
  name: vagrant
  network:
    - ["private_network", { type: "dhcp" }]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  environments_path: test/environments
  client_rb:
    environment: kitchen
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[keycloak::default]
    attributes:
